# NOTE: This file is auto generated by OpenAPI Generator 6.5.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ApacheIcebergRESTCatalogAPI.Model.AddSchemaUpdateAllOf do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :schema
  ]

  @type t :: %__MODULE__{
    :schema => ApacheIcebergRESTCatalogAPI.Model.Schema.t
  }
end

defimpl Poison.Decoder, for: ApacheIcebergRESTCatalogAPI.Model.AddSchemaUpdateAllOf do
  import ApacheIcebergRESTCatalogAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:schema, :struct, ApacheIcebergRESTCatalogAPI.Model.Schema, options)
  end
end

