# NOTE: This file is auto generated by OpenAPI Generator 6.5.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ApacheIcebergRESTCatalogAPI.Model.AddSnapshotUpdateAllOf do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :snapshot
  ]

  @type t :: %__MODULE__{
    :snapshot => ApacheIcebergRESTCatalogAPI.Model.Snapshot.t
  }
end

defimpl Poison.Decoder, for: ApacheIcebergRESTCatalogAPI.Model.AddSnapshotUpdateAllOf do
  import ApacheIcebergRESTCatalogAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:snapshot, :struct, ApacheIcebergRESTCatalogAPI.Model.Snapshot, options)
  end
end

