# NOTE: This file is auto generated by OpenAPI Generator 6.5.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ApacheIcebergRESTCatalogAPI.Model.AndOrExpression do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :type,
    :left,
    :right
  ]

  @type t :: %__MODULE__{
    :type => String.t,
    :left => ApacheIcebergRESTCatalogAPI.Model.Expression.t,
    :right => ApacheIcebergRESTCatalogAPI.Model.Expression.t
  }
end

defimpl Poison.Decoder, for: ApacheIcebergRESTCatalogAPI.Model.AndOrExpression do
  import ApacheIcebergRESTCatalogAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:left, :struct, ApacheIcebergRESTCatalogAPI.Model.Expression, options)
    |> deserialize(:right, :struct, ApacheIcebergRESTCatalogAPI.Model.Expression, options)
  end
end

