# NOTE: This file is auto generated by OpenAPI Generator 6.5.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ApacheIcebergRESTCatalogAPI.Model.CatalogConfig do
  @moduledoc """
  Server-provided configuration for the catalog.
  """

  @derive [Poison.Encoder]
  defstruct [
    :overrides,
    :defaults
  ]

  @type t :: %__MODULE__{
    :overrides => %{optional(String.t) => String.t},
    :defaults => %{optional(String.t) => String.t}
  }
end

defimpl Poison.Decoder, for: ApacheIcebergRESTCatalogAPI.Model.CatalogConfig do
  def decode(value, _options) do
    value
  end
end

