# NOTE: This file is auto generated by OpenAPI Generator 6.5.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ApacheIcebergRESTCatalogAPI.Model.CommitTableRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :requirements,
    :updates
  ]

  @type t :: %__MODULE__{
    :requirements => [ApacheIcebergRESTCatalogAPI.Model.TableRequirement.t],
    :updates => [ApacheIcebergRESTCatalogAPI.Model.TableUpdate.t]
  }
end

defimpl Poison.Decoder, for: ApacheIcebergRESTCatalogAPI.Model.CommitTableRequest do
  import ApacheIcebergRESTCatalogAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:requirements, :list, ApacheIcebergRESTCatalogAPI.Model.TableRequirement, options)
    |> deserialize(:updates, :list, ApacheIcebergRESTCatalogAPI.Model.TableUpdate, options)
  end
end

