# NOTE: This file is auto generated by OpenAPI Generator 6.5.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ApacheIcebergRESTCatalogAPI.Model.CommitReport do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"table-name",
    :"snapshot-id",
    :"sequence-number",
    :operation,
    :metrics,
    :metadata
  ]

  @type t :: %__MODULE__{
    :"table-name" => String.t,
    :"snapshot-id" => integer(),
    :"sequence-number" => integer(),
    :operation => String.t,
    :metrics => %{optional(String.t) => ApacheIcebergRESTCatalogAPI.Model.MetricResult.t},
    :metadata => %{optional(String.t) => String.t} | nil
  }
end

defimpl Poison.Decoder, for: ApacheIcebergRESTCatalogAPI.Model.CommitReport do
  import ApacheIcebergRESTCatalogAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:metrics, :map, ApacheIcebergRESTCatalogAPI.Model.MetricResult, options)
  end
end

