# NOTE: This file is auto generated by OpenAPI Generator 6.5.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ApacheIcebergRESTCatalogAPI.Model.CreateNamespaceRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :namespace,
    :properties
  ]

  @type t :: %__MODULE__{
    :namespace => [String.t],
    :properties => %{optional(String.t) => String.t} | nil
  }
end

defimpl Poison.Decoder, for: ApacheIcebergRESTCatalogAPI.Model.CreateNamespaceRequest do
  def decode(value, _options) do
    value
  end
end

