# NOTE: This file is auto generated by OpenAPI Generator 6.5.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ApacheIcebergRESTCatalogAPI.Model.CreateTableRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :name,
    :location,
    :schema,
    :"partition-spec",
    :"write-order",
    :"stage-create",
    :properties
  ]

  @type t :: %__MODULE__{
    :name => String.t,
    :location => String.t | nil,
    :schema => ApacheIcebergRESTCatalogAPI.Model.Schema.t,
    :"partition-spec" => ApacheIcebergRESTCatalogAPI.Model.PartitionSpec.t | nil,
    :"write-order" => ApacheIcebergRESTCatalogAPI.Model.SortOrder.t | nil,
    :"stage-create" => boolean() | nil,
    :properties => %{optional(String.t) => String.t} | nil
  }
end

defimpl Poison.Decoder, for: ApacheIcebergRESTCatalogAPI.Model.CreateTableRequest do
  import ApacheIcebergRESTCatalogAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:schema, :struct, ApacheIcebergRESTCatalogAPI.Model.Schema, options)
    |> deserialize(:"partition-spec", :struct, ApacheIcebergRESTCatalogAPI.Model.PartitionSpec, options)
    |> deserialize(:"write-order", :struct, ApacheIcebergRESTCatalogAPI.Model.SortOrder, options)
  end
end

