# NOTE: This file is auto generated by OpenAPI Generator 6.5.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ApacheIcebergRESTCatalogAPI.Model.Expression do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :type,
    :left,
    :right,
    :child,
    :term,
    :values,
    :value
  ]

  @type t :: %__MODULE__{
    :type => String.t,
    :left => ApacheIcebergRESTCatalogAPI.Model.Expression.t,
    :right => ApacheIcebergRESTCatalogAPI.Model.Expression.t,
    :child => ApacheIcebergRESTCatalogAPI.Model.Expression.t,
    :term => ApacheIcebergRESTCatalogAPI.Model.Term.t,
    :values => [map()],
    :value => map()
  }
end

defimpl Poison.Decoder, for: ApacheIcebergRESTCatalogAPI.Model.Expression do
  import ApacheIcebergRESTCatalogAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:left, :struct, ApacheIcebergRESTCatalogAPI.Model.Expression, options)
    |> deserialize(:right, :struct, ApacheIcebergRESTCatalogAPI.Model.Expression, options)
    |> deserialize(:child, :struct, ApacheIcebergRESTCatalogAPI.Model.Expression, options)
    |> deserialize(:term, :struct, ApacheIcebergRESTCatalogAPI.Model.Term, options)
  end
end

