# NOTE: This file is auto generated by OpenAPI Generator 6.5.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ApacheIcebergRESTCatalogAPI.Model.GetToken400Response do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :error,
    :error_description,
    :error_uri
  ]

  @type t :: %__MODULE__{
    :error => String.t,
    :error_description => String.t | nil,
    :error_uri => String.t | nil
  }
end

defimpl Poison.Decoder, for: ApacheIcebergRESTCatalogAPI.Model.GetToken400Response do
  def decode(value, _options) do
    value
  end
end

