# NOTE: This file is auto generated by OpenAPI Generator 6.5.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ApacheIcebergRESTCatalogAPI.Model.GetToken200Response do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :access_token,
    :token_type,
    :expires_in,
    :issued_token_type,
    :refresh_token,
    :scope
  ]

  @type t :: %__MODULE__{
    :access_token => String.t,
    :token_type => String.t,
    :expires_in => integer() | nil,
    :issued_token_type => ApacheIcebergRESTCatalogAPI.Model.TokenType.t | nil,
    :refresh_token => String.t | nil,
    :scope => String.t | nil
  }
end

defimpl Poison.Decoder, for: ApacheIcebergRESTCatalogAPI.Model.GetToken200Response do
  import ApacheIcebergRESTCatalogAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:issued_token_type, :struct, ApacheIcebergRESTCatalogAPI.Model.TokenType, options)
  end
end

