# NOTE: This file is auto generated by OpenAPI Generator 6.5.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ApacheIcebergRESTCatalogAPI.Model.ListType do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :type,
    :"element-id",
    :element,
    :"element-required"
  ]

  @type t :: %__MODULE__{
    :type => String.t,
    :"element-id" => integer(),
    :element => ApacheIcebergRESTCatalogAPI.Model.Type.t,
    :"element-required" => boolean()
  }
end

defimpl Poison.Decoder, for: ApacheIcebergRESTCatalogAPI.Model.ListType do
  import ApacheIcebergRESTCatalogAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:element, :struct, ApacheIcebergRESTCatalogAPI.Model.Type, options)
  end
end

