# NOTE: This file is auto generated by OpenAPI Generator 6.5.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ApacheIcebergRESTCatalogAPI.Model.MetadataLogInner do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"metadata-file",
    :"timestamp-ms"
  ]

  @type t :: %__MODULE__{
    :"metadata-file" => String.t,
    :"timestamp-ms" => integer()
  }
end

defimpl Poison.Decoder, for: ApacheIcebergRESTCatalogAPI.Model.MetadataLogInner do
  def decode(value, _options) do
    value
  end
end

