# NOTE: This file is auto generated by OpenAPI Generator 6.5.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ApacheIcebergRESTCatalogAPI.Model.PartitionSpec do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"spec-id",
    :fields
  ]

  @type t :: %__MODULE__{
    :"spec-id" => integer() | nil,
    :fields => [ApacheIcebergRESTCatalogAPI.Model.PartitionField.t]
  }
end

defimpl Poison.Decoder, for: ApacheIcebergRESTCatalogAPI.Model.PartitionSpec do
  import ApacheIcebergRESTCatalogAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:fields, :list, ApacheIcebergRESTCatalogAPI.Model.PartitionField, options)
  end
end

