# NOTE: This file is auto generated by OpenAPI Generator 6.5.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ApacheIcebergRESTCatalogAPI.Model.PartitionField do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"field-id",
    :"source-id",
    :name,
    :transform
  ]

  @type t :: %__MODULE__{
    :"field-id" => integer() | nil,
    :"source-id" => integer(),
    :name => String.t,
    :transform => String.t
  }
end

defimpl Poison.Decoder, for: ApacheIcebergRESTCatalogAPI.Model.PartitionField do
  def decode(value, _options) do
    value
  end
end

