# NOTE: This file is auto generated by OpenAPI Generator 6.5.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ApacheIcebergRESTCatalogAPI.Model.RemovePropertiesUpdateAllOf do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :removals
  ]

  @type t :: %__MODULE__{
    :removals => [String.t]
  }
end

defimpl Poison.Decoder, for: ApacheIcebergRESTCatalogAPI.Model.RemovePropertiesUpdateAllOf do
  def decode(value, _options) do
    value
  end
end

