# NOTE: This file is auto generated by OpenAPI Generator 6.5.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ApacheIcebergRESTCatalogAPI.Model.RenameTableRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :source,
    :destination
  ]

  @type t :: %__MODULE__{
    :source => ApacheIcebergRESTCatalogAPI.Model.TableIdentifier.t,
    :destination => ApacheIcebergRESTCatalogAPI.Model.TableIdentifier.t
  }
end

defimpl Poison.Decoder, for: ApacheIcebergRESTCatalogAPI.Model.RenameTableRequest do
  import ApacheIcebergRESTCatalogAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:source, :struct, ApacheIcebergRESTCatalogAPI.Model.TableIdentifier, options)
    |> deserialize(:destination, :struct, ApacheIcebergRESTCatalogAPI.Model.TableIdentifier, options)
  end
end

