# NOTE: This file is auto generated by OpenAPI Generator 6.5.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ApacheIcebergRESTCatalogAPI.Model.SchemaAllOf do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"schema-id",
    :"identifier-field-ids"
  ]

  @type t :: %__MODULE__{
    :"schema-id" => integer() | nil,
    :"identifier-field-ids" => [integer()] | nil
  }
end

defimpl Poison.Decoder, for: ApacheIcebergRESTCatalogAPI.Model.SchemaAllOf do
  def decode(value, _options) do
    value
  end
end

