# NOTE: This file is auto generated by OpenAPI Generator 6.5.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ApacheIcebergRESTCatalogAPI.Model.Schema do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :type,
    :fields,
    :"schema-id",
    :"identifier-field-ids"
  ]

  @type t :: %__MODULE__{
    :type => String.t,
    :fields => [ApacheIcebergRESTCatalogAPI.Model.StructField.t],
    :"schema-id" => integer() | nil,
    :"identifier-field-ids" => [integer()] | nil
  }
end

defimpl Poison.Decoder, for: ApacheIcebergRESTCatalogAPI.Model.Schema do
  import ApacheIcebergRESTCatalogAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:fields, :list, ApacheIcebergRESTCatalogAPI.Model.StructField, options)
  end
end

