# NOTE: This file is auto generated by OpenAPI Generator 6.5.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ApacheIcebergRESTCatalogAPI.Model.SetSnapshotRefUpdateAllOf do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"ref-name"
  ]

  @type t :: %__MODULE__{
    :"ref-name" => String.t
  }
end

defimpl Poison.Decoder, for: ApacheIcebergRESTCatalogAPI.Model.SetSnapshotRefUpdateAllOf do
  def decode(value, _options) do
    value
  end
end

