# NOTE: This file is auto generated by OpenAPI Generator 6.5.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ApacheIcebergRESTCatalogAPI.Model.SetDefaultSpecUpdate do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :action,
    :"spec-id"
  ]

  @type t :: %__MODULE__{
    :action => String.t,
    :"spec-id" => integer()
  }
end

defimpl Poison.Decoder, for: ApacheIcebergRESTCatalogAPI.Model.SetDefaultSpecUpdate do
  def decode(value, _options) do
    value
  end
end

