# NOTE: This file is auto generated by OpenAPI Generator 6.5.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ApacheIcebergRESTCatalogAPI.Model.SetSnapshotRefUpdate do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :action,
    :type,
    :"snapshot-id",
    :"max-ref-age-ms",
    :"max-snapshot-age-ms",
    :"min-snapshots-to-keep",
    :"ref-name"
  ]

  @type t :: %__MODULE__{
    :action => String.t,
    :type => String.t,
    :"snapshot-id" => integer(),
    :"max-ref-age-ms" => integer() | nil,
    :"max-snapshot-age-ms" => integer() | nil,
    :"min-snapshots-to-keep" => integer() | nil,
    :"ref-name" => String.t
  }
end

defimpl Poison.Decoder, for: ApacheIcebergRESTCatalogAPI.Model.SetSnapshotRefUpdate do
  def decode(value, _options) do
    value
  end
end

