# NOTE: This file is auto generated by OpenAPI Generator 6.5.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ApacheIcebergRESTCatalogAPI.Model.SetPropertiesUpdateAllOf do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :updates
  ]

  @type t :: %__MODULE__{
    :updates => %{optional(String.t) => String.t}
  }
end

defimpl Poison.Decoder, for: ApacheIcebergRESTCatalogAPI.Model.SetPropertiesUpdateAllOf do
  def decode(value, _options) do
    value
  end
end

