# NOTE: This file is auto generated by OpenAPI Generator 6.5.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ApacheIcebergRESTCatalogAPI.Model.Snapshot do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"snapshot-id",
    :"parent-snapshot-id",
    :"sequence-number",
    :"timestamp-ms",
    :"manifest-list",
    :summary,
    :"schema-id"
  ]

  @type t :: %__MODULE__{
    :"snapshot-id" => integer(),
    :"parent-snapshot-id" => integer() | nil,
    :"sequence-number" => integer() | nil,
    :"timestamp-ms" => integer(),
    :"manifest-list" => String.t,
    :summary => ApacheIcebergRESTCatalogAPI.Model.SnapshotSummary.t,
    :"schema-id" => integer() | nil
  }
end

defimpl Poison.Decoder, for: ApacheIcebergRESTCatalogAPI.Model.Snapshot do
  import ApacheIcebergRESTCatalogAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:summary, :struct, ApacheIcebergRESTCatalogAPI.Model.SnapshotSummary, options)
  end
end

