# NOTE: This file is auto generated by OpenAPI Generator 6.5.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ApacheIcebergRESTCatalogAPI.Model.SnapshotSummary do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :operation,
    :additionalProperties
  ]

  @type t :: %__MODULE__{
    :operation => String.t,
    :additionalProperties => String.t | nil
  }
end

defimpl Poison.Decoder, for: ApacheIcebergRESTCatalogAPI.Model.SnapshotSummary do
  def decode(value, _options) do
    value
  end
end

