# NOTE: This file is auto generated by OpenAPI Generator 6.5.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ApacheIcebergRESTCatalogAPI.Model.SortField do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"source-id",
    :transform,
    :direction,
    :"null-order"
  ]

  @type t :: %__MODULE__{
    :"source-id" => integer(),
    :transform => String.t,
    :direction => ApacheIcebergRESTCatalogAPI.Model.SortDirection.t,
    :"null-order" => ApacheIcebergRESTCatalogAPI.Model.NullOrder.t
  }
end

defimpl Poison.Decoder, for: ApacheIcebergRESTCatalogAPI.Model.SortField do
  import ApacheIcebergRESTCatalogAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:direction, :struct, ApacheIcebergRESTCatalogAPI.Model.SortDirection, options)
    |> deserialize(:"null-order", :struct, ApacheIcebergRESTCatalogAPI.Model.NullOrder, options)
  end
end

