# NOTE: This file is auto generated by OpenAPI Generator 6.5.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ApacheIcebergRESTCatalogAPI.Model.SortOrder do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"order-id",
    :fields
  ]

  @type t :: %__MODULE__{
    :"order-id" => integer(),
    :fields => [ApacheIcebergRESTCatalogAPI.Model.SortField.t]
  }
end

defimpl Poison.Decoder, for: ApacheIcebergRESTCatalogAPI.Model.SortOrder do
  import ApacheIcebergRESTCatalogAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:fields, :list, ApacheIcebergRESTCatalogAPI.Model.SortField, options)
  end
end

