# NOTE: This file is auto generated by OpenAPI Generator 6.5.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ApacheIcebergRESTCatalogAPI.Model.StructField do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :name,
    :type,
    :required,
    :doc
  ]

  @type t :: %__MODULE__{
    :id => integer(),
    :name => String.t,
    :type => ApacheIcebergRESTCatalogAPI.Model.Type.t,
    :required => boolean(),
    :doc => String.t | nil
  }
end

defimpl Poison.Decoder, for: ApacheIcebergRESTCatalogAPI.Model.StructField do
  import ApacheIcebergRESTCatalogAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:type, :struct, ApacheIcebergRESTCatalogAPI.Model.Type, options)
  end
end

