# NOTE: This file is auto generated by OpenAPI Generator 6.5.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ApacheIcebergRESTCatalogAPI.Model.TableMetadata do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"format-version",
    :"table-uuid",
    :location,
    :"last-updated-ms",
    :properties,
    :schemas,
    :"current-schema-id",
    :"last-column-id",
    :"partition-specs",
    :"default-spec-id",
    :"last-partition-id",
    :"sort-orders",
    :"default-sort-order-id",
    :snapshots,
    :refs,
    :"current-snapshot-id",
    :"snapshot-log",
    :"metadata-log"
  ]

  @type t :: %__MODULE__{
    :"format-version" => integer(),
    :"table-uuid" => String.t,
    :location => String.t | nil,
    :"last-updated-ms" => integer() | nil,
    :properties => %{optional(String.t) => String.t} | nil,
    :schemas => [ApacheIcebergRESTCatalogAPI.Model.Schema.t] | nil,
    :"current-schema-id" => integer() | nil,
    :"last-column-id" => integer() | nil,
    :"partition-specs" => [ApacheIcebergRESTCatalogAPI.Model.PartitionSpec.t] | nil,
    :"default-spec-id" => integer() | nil,
    :"last-partition-id" => integer() | nil,
    :"sort-orders" => [ApacheIcebergRESTCatalogAPI.Model.SortOrder.t] | nil,
    :"default-sort-order-id" => integer() | nil,
    :snapshots => [ApacheIcebergRESTCatalogAPI.Model.Snapshot.t] | nil,
    :refs => %{optional(String.t) => ApacheIcebergRESTCatalogAPI.Model.SnapshotReference.t} | nil,
    :"current-snapshot-id" => integer() | nil,
    :"snapshot-log" => [ApacheIcebergRESTCatalogAPI.Model.SnapshotLogInner.t] | nil,
    :"metadata-log" => [ApacheIcebergRESTCatalogAPI.Model.MetadataLogInner.t] | nil
  }
end

defimpl Poison.Decoder, for: ApacheIcebergRESTCatalogAPI.Model.TableMetadata do
  import ApacheIcebergRESTCatalogAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:schemas, :list, ApacheIcebergRESTCatalogAPI.Model.Schema, options)
    |> deserialize(:"partition-specs", :list, ApacheIcebergRESTCatalogAPI.Model.PartitionSpec, options)
    |> deserialize(:"sort-orders", :list, ApacheIcebergRESTCatalogAPI.Model.SortOrder, options)
    |> deserialize(:snapshots, :list, ApacheIcebergRESTCatalogAPI.Model.Snapshot, options)
    |> deserialize(:refs, :map, ApacheIcebergRESTCatalogAPI.Model.SnapshotReference, options)
    |> deserialize(:"snapshot-log", :list, ApacheIcebergRESTCatalogAPI.Model.SnapshotLogInner, options)
    |> deserialize(:"metadata-log", :list, ApacheIcebergRESTCatalogAPI.Model.MetadataLogInner, options)
  end
end

