# NOTE: This file is auto generated by OpenAPI Generator 6.5.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ApacheIcebergRESTCatalogAPI.Model.TableUpdate do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :action,
    :"format-version",
    :schema,
    :"schema-id",
    :spec,
    :"spec-id",
    :"sort-order",
    :"sort-order-id",
    :snapshot,
    :type,
    :"snapshot-id",
    :"max-ref-age-ms",
    :"max-snapshot-age-ms",
    :"min-snapshots-to-keep",
    :"ref-name",
    :"snapshot-ids",
    :location,
    :updates,
    :removals
  ]

  @type t :: %__MODULE__{
    :action => String.t,
    :"format-version" => integer(),
    :schema => ApacheIcebergRESTCatalogAPI.Model.Schema.t,
    :"schema-id" => integer(),
    :spec => ApacheIcebergRESTCatalogAPI.Model.PartitionSpec.t,
    :"spec-id" => integer(),
    :"sort-order" => ApacheIcebergRESTCatalogAPI.Model.SortOrder.t,
    :"sort-order-id" => integer(),
    :snapshot => ApacheIcebergRESTCatalogAPI.Model.Snapshot.t,
    :type => String.t,
    :"snapshot-id" => integer(),
    :"max-ref-age-ms" => integer() | nil,
    :"max-snapshot-age-ms" => integer() | nil,
    :"min-snapshots-to-keep" => integer() | nil,
    :"ref-name" => String.t,
    :"snapshot-ids" => [integer()],
    :location => String.t,
    :updates => %{optional(String.t) => String.t},
    :removals => [String.t]
  }
end

defimpl Poison.Decoder, for: ApacheIcebergRESTCatalogAPI.Model.TableUpdate do
  import ApacheIcebergRESTCatalogAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:schema, :struct, ApacheIcebergRESTCatalogAPI.Model.Schema, options)
    |> deserialize(:spec, :struct, ApacheIcebergRESTCatalogAPI.Model.PartitionSpec, options)
    |> deserialize(:"sort-order", :struct, ApacheIcebergRESTCatalogAPI.Model.SortOrder, options)
    |> deserialize(:snapshot, :struct, ApacheIcebergRESTCatalogAPI.Model.Snapshot, options)
  end
end

