# NOTE: This file is auto generated by OpenAPI Generator 6.5.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ApacheIcebergRESTCatalogAPI.Model.TableIdentifier do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :namespace,
    :name
  ]

  @type t :: %__MODULE__{
    :namespace => [String.t],
    :name => String.t
  }
end

defimpl Poison.Decoder, for: ApacheIcebergRESTCatalogAPI.Model.TableIdentifier do
  def decode(value, _options) do
    value
  end
end

