# NOTE: This file is auto generated by OpenAPI Generator 6.5.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ApacheIcebergRESTCatalogAPI.Model.UpdateTable200Response do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"metadata-location",
    :metadata
  ]

  @type t :: %__MODULE__{
    :"metadata-location" => String.t,
    :metadata => ApacheIcebergRESTCatalogAPI.Model.TableMetadata.t
  }
end

defimpl Poison.Decoder, for: ApacheIcebergRESTCatalogAPI.Model.UpdateTable200Response do
  import ApacheIcebergRESTCatalogAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:metadata, :struct, ApacheIcebergRESTCatalogAPI.Model.TableMetadata, options)
  end
end

