# NOTE: This file is auto generated by OpenAPI Generator 6.5.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ApacheIcebergRESTCatalogAPI.Model.UpdateProperties200Response do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :updated,
    :removed,
    :missing
  ]

  @type t :: %__MODULE__{
    :updated => [String.t],
    :removed => [String.t],
    :missing => [String.t] | nil
  }
end

defimpl Poison.Decoder, for: ApacheIcebergRESTCatalogAPI.Model.UpdateProperties200Response do
  def decode(value, _options) do
    value
  end
end

